<html>
<head>
    <script src="../js/zepto.min.js"></script>
</head>
<body>
First name: <input type="text" name="userName" id="userName" value="heqiang"/><br/>
Last name: <input type="text" name="password" id="password"/><br/>
<input type="button" value="Submit" onclick="login()"/>

<script>
     function login() {
        var userName = $("#userName").val();
        var password = $("#password").val();
        if(String.empty(userName)){
            alert('用户名不能为空.')
            return ;
        }

        $.ajax({
            type: 'POST',
            url: 'http://localhost:80/user/login',
            data: {"userName": userName, "password": password},
            dataType: 'JSON',
            success: function (data) {
                var result = $.parseJSON(data);
                if (result.code == 0) {
                    alert(result.message);
                } else {
                    alert(result.message);
                }
            },
            error: function (xhr, type) {
                alert('Ajax error!')
            }
        })
    }

</script>


</body>
</html>