<html>
<body>

<form action="/question/answer" method="post"
      enctype="multipart/form-data">
    <label for="file">Filename:</label>
    <input type="file" name="file" id="file" /><br />
    basePrice: <input type="text" name="basePrice" /><br />
    addPrice: <input type="text" name="addPrice" /><br />
    listenPrice: <input type="text" name="listenPrice" /><br />
    content: <input type="text" name="content" /><br />
    state: <input type="text" name="state" /><br />
    type: <input type="text" name="type" /><br />
    questionId: <input type="text" name="questionId" /><br />
    <br />
    <input type="submit" name="submit" value="Submit" />
</form>

</body>
</html>