<html>
<body>

<form action="/question/submit" method="post"
      enctype="multipart/form-data">
    <label for="file">Filename:</label>
    <input type="file" name="file" id="file" /><br />
    basePrice: <input type="text" name="basePrice" /><br />
    addPrice: <input type="text" name="addPrice" /><br />
    content: <input type="text" name="content" /><br />
    <br />
    <input type="submit" name="submit" value="Submit" />
</form>
</body>
</html>