
<!--<html>-->
<!--<head>-->
<!--    <title>Hello World</title>-->
<!--</head>-->
<!--<body>-->
<?php //echo $content;?>
<!--</body>-->
<!--</html>-->

<!--<html>-->
<!--<body>-->
<!---->
<!--<form action="/login" method="post" target="_blank">-->
<!--    First name: <input type="text" name="userName" /><br />-->
<!--    Last name: <input type="text" name="password" /><br />-->
<!--    <input type="submit" value="Submit" />-->
<!--</form>-->
<!---->
<!--</body>-->
<!--</html>-->



<html>
<body>

<form action="http://www.youdi.com/question/submit" method="post"
      enctype="multipart/form-data">
    <label for="file">Filename:</label>
    <input type="file" name="file" id="file" /><br />
    basePrice: <input type="text" name="basePrice" /><br />
    addPrice: <input type="text" name="addPrice" /><br />
    content: <input type="text" name="content" /><br />
    <br />
    <input type="submit" name="submit" value="Submit" />
</form>

</body>
</html>
